[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
my_crud_app = "5M6eZAZGTHczF2JH3PEEWB5tEWxZmCepNHobjPDKjNVz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/decaff/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
